(() => {
const modules = window.STUDY_MODULES || [];
const questions = window.QUESTION_BANK || [];
const cards = window.VOCAB_CARDS || [];
const KEY='toeicStudyStateV1';
const defaultState={completed:[],answerLog:{},wrongIds:[],masteredCards:[],lastModule:'priority',visits:[],theme:'light'};
let state=loadState();
let currentView='dashboard',currentModule=null,quizSession=null,flashDeck=[],flashIndex=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return {...defaultState}}}
function saveState(){localStorage.setItem(KEY,JSON.stringify(state));refreshStats()}
function today(){return new Date().toISOString().slice(0,10)}
function updateVisit(){const d=today();if(!state.visits.includes(d)){state.visits.push(d);state.visits=state.visits.slice(-60);saveState()}}
function streak(){const dates=new Set(state.visits);let n=0,d=new Date();while(dates.has(d.toISOString().slice(0,10))){n++;d.setDate(d.getDate()-1)}return Math.max(n,1)}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function stripHTML(s){const d=document.createElement('div');d.innerHTML=s;return d.textContent||''}
function moduleById(id){return modules.find(m=>m.id===id)}
function moduleTitle(id){return moduleById(id)?.title||id}
function stars(n){return '★'.repeat(n)+'☆'.repeat(3-n)}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),1900)}
function showView(view){currentView=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(view==='course')renderCourseNav();if(view==='mistakes')renderMistakes();if(view==='flashcards')initFlashcards();if(view==='quiz')updateQuizAvailability()}
function refreshStats(){const totalAnswers=Object.values(state.answerLog).reduce((s,x)=>s+(x.attempts||0),0);const correct=Object.values(state.answerLog).reduce((s,x)=>s+(x.correct||0),0);const pct=Math.round((state.completed.length/modules.length)*100);$('#statModules').textContent=`${state.completed.length} / ${modules.length}`;$('#statAnswers').textContent=totalAnswers;$('#statAccuracy').textContent=totalAnswers?`${Math.round(correct/totalAnswers*100)}%`:'—';$('#statStreak').textContent=`${streak()} 天`;$('#heroPercent').textContent=`${pct}%`;$('.ring').style.setProperty('--progress',`${pct}%`);$('#coursePercent').textContent=`${pct}%`;$('#sideProgress').style.width=`${pct}%`;$('#sideProgressText').textContent=pct?`已完成 ${pct}%`:'尚未開始';$('#wrongBadge').textContent=state.wrongIds.length;$('#quickWrongText').textContent=state.wrongIds.length?`${state.wrongIds.length} 題等待複習`:'目前沒有錯題';$('#flashMastered').textContent=state.masteredCards.length;renderRecommendations();renderModulePreview()}
function renderRecommendations(){const el=$('#recommendations');if(!el)return;const scored=modules.filter(m=>m.id!=='priority'&&m.id!=='checklist').map(m=>{const qs=questions.filter(q=>q.module===m.id);let attempts=0,correct=0;qs.forEach(q=>{const l=state.answerLog[q.id];if(l){attempts+=l.attempts||0;correct+=l.correct||0}});const accuracy=attempts?correct/attempts:null;let score=(m.priority*2)+(state.completed.includes(m.id)?-3:2)+(accuracy!==null?(1-accuracy)*8:0);return {m,score,accuracy,attempts}}).sort((a,b)=>b.score-a.score).slice(0,3);el.innerHTML=scored.map((x,i)=>`<button class="recommendation" data-module="${x.m.id}"><span class="rec-num">${i+1}</span><div><b>${escapeHTML(x.m.title)}</b><small>${x.attempts?`目前正確率 ${Math.round(x.accuracy*100)}%`:`約 ${x.m.estimated} 分鐘，尚未完成`}</small></div><span class="stars">${stars(x.m.priority)}</span></button>`).join('');$$('.recommendation').forEach(b=>b.onclick=()=>openModule(b.dataset.module))}
function renderModulePreview(){const el=$('#modulePreview');if(!el)return;el.innerHTML=modules.filter(m=>m.priority===3).slice(0,8).map(m=>moduleCardHTML(m)).join('');$$('#modulePreview .module-card').forEach(c=>c.onclick=()=>openModule(c.dataset.module))}
function moduleCardHTML(m){const done=state.completed.includes(m.id);return `<article class="module-card" data-module="${m.id}">${done?'<span class="done-check">✓</span>':''}<div class="module-meta"><span>${escapeHTML(m.group)}</span><span>${m.estimated} 分鐘</span></div><h3>${escapeHTML(m.title)}</h3><p>${escapeHTML(m.subtitle)}</p><div class="stars" style="margin-top:10px">${stars(m.priority)}</div></article>`}
function renderCourseNav(){const nav=$('#courseNav');let html='',last='';modules.forEach(m=>{if(m.group!==last){last=m.group;html+=`<div class="course-group">${escapeHTML(last)}</div>`}const done=state.completed.includes(m.id);html+=`<button class="course-link ${done?'completed':''} ${currentModule===m.id?'active':''}" data-module="${m.id}"><span class="course-dot">${done?'✓':''}</span><span><b>${escapeHTML(m.title)}</b><small>${stars(m.priority)} · ${m.estimated} 分鐘</small></span></button>`});nav.innerHTML=html;$$('.course-link').forEach(b=>b.onclick=()=>renderLesson(b.dataset.module))}
function openModule(id){showView('course');renderLesson(id)}
function renderLesson(id){const m=moduleById(id);if(!m)return;currentModule=id;state.lastModule=id;saveState();renderCourseNav();const done=state.completed.includes(id);$('#lessonArticle').innerHTML=`<header class="lesson-header"><span class="eyebrow">${escapeHTML(m.group)}</span><h1>${escapeHTML(m.title)}</h1><p>${escapeHTML(m.subtitle)}</p><div class="lesson-toolbar"><span class="source-pill">資料來源：${escapeHTML(m.source)} · 約 ${m.estimated} 分鐘</span><button class="btn secondary complete-btn ${done?'completed':''}" id="completeLesson">${done?'✓ 已完成':'標記為已完成'}</button></div></header><div class="lesson-content">${m.content}</div><footer class="lesson-bottom"><button class="btn secondary" id="lessonQuiz">練習本章題目</button><button class="btn primary" id="nextLesson">下一章 →</button></footer>`;$('#completeLesson').onclick=()=>toggleComplete(id);$('#lessonQuiz').onclick=()=>startQuiz('module',10,id);$('#nextLesson').onclick=()=>{const i=modules.findIndex(x=>x.id===id);renderLesson(modules[(i+1)%modules.length].id);window.scrollTo({top:0,behavior:'smooth'})}}
function toggleComplete(id){if(state.completed.includes(id))state.completed=state.completed.filter(x=>x!==id);else state.completed.push(id);saveState();renderLesson(id);toast(state.completed.includes(id)?'已完成本章':'已取消完成標記')}
function setMode(mode){$$('.mode-card').forEach(l=>l.classList.toggle('selected',l.querySelector('input').value===mode));const input=$(`input[name="quizMode"][value="${mode}"]`);if(input)input.checked=true;$('#quizModule').disabled=mode!=='module';updateQuizAvailability()}
function availableQuestions(mode,moduleId){if(mode==='wrong')return questions.filter(q=>state.wrongIds.includes(q.id));if(mode==='module')return questions.filter(q=>q.module===moduleId);return questions}
function updateQuizAvailability(){const mode=$('input[name="quizMode"]:checked')?.value||'mixed',mid=$('#quizModule')?.value;const n=availableQuestions(mode,mid).length;const hint=$('#quizAvailability');if(hint)hint.textContent=mode==='wrong'&&!n?'目前沒有錯題，先完成一回混合練習。':`目前可出 ${n} 題。`}
function prepareQuestion(raw){const items=raw.choices.map((text,i)=>({text,correct:i===raw.answer}));return {...raw,shuffled:shuffle(items)}}
function startQuiz(mode='mixed',count=10,moduleId=null){showView('quiz');const pool=availableQuestions(mode,moduleId||$('#quizModule').value);if(!pool.length){toast('目前沒有可用題目');return}const picked=shuffle(pool).slice(0,Math.min(Number(count)||10,pool.length)).map(prepareQuestion);quizSession={mode,moduleId,questions:picked,index:0,correct:0,answers:[]};$('#quizSetup').hidden=true;$('#quizRunner').hidden=false;renderQuestion()}
function renderQuestion(){const s=quizSession;if(s.index>=s.questions.length)return renderResult();const q=s.questions[s.index],m=moduleById(q.module);$('#quizRunner').innerHTML=`<div class="quiz-shell"><div class="quiz-top"><span class="quiz-number">${s.index+1} / ${s.questions.length}</span><div class="quiz-progress"><span style="width:${(s.index/s.questions.length)*100}%"></span></div><button class="text-btn" id="quitQuiz">結束</button></div><article class="question-card"><span class="question-category">${escapeHTML(m?.title||q.module)} · 難度 ${'●'.repeat(q.level||1)}</span><h2>${escapeHTML(q.prompt)}</h2><div class="choices">${q.shuffled.map((c,i)=>`<button class="choice" data-i="${i}"><span class="choice-letter">${String.fromCharCode(65+i)}</span><span>${escapeHTML(c.text)}</span></button>`).join('')}</div><div class="feedback" id="feedback"></div><div class="question-actions"><button class="btn primary" id="nextQuestion" hidden>${s.index===s.questions.length-1?'查看結果':'下一題 →'}</button></div></article></div>`;$$('.choice').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.i)));$('#nextQuestion').onclick=()=>{s.index++;renderQuestion()};$('#quitQuiz').onclick=()=>{if(confirm('要結束這次練習嗎？'))resetQuiz()}}
function answerQuestion(i){const s=quizSession,q=s.questions[s.index],selected=q.shuffled[i],correct=selected.correct;$$('.choice').forEach((b,idx)=>{b.disabled=true;if(q.shuffled[idx].correct)b.classList.add('correct');else if(idx===i)b.classList.add('wrong')});const fb=$('#feedback');fb.className=`feedback show ${correct?'correct':'wrong'}`;fb.innerHTML=`<h3>${correct?'答對了！':'答錯了'}</h3><p>${escapeHTML(q.explanation)}</p>${q.tip?`<p class="tip"><b>秒判提示：</b>${escapeHTML(q.tip)}</p>`:''}`;$('#nextQuestion').hidden=false;s.answers.push({id:q.id,correct});if(correct)s.correct++;const log=state.answerLog[q.id]||{attempts:0,correct:0};log.attempts++;if(correct)log.correct++;log.last=today();state.answerLog[q.id]=log;if(correct){state.wrongIds=state.wrongIds.filter(x=>x!==q.id)}else if(!state.wrongIds.includes(q.id)){state.wrongIds.push(q.id)}saveState()}
function renderResult(){const s=quizSession,pct=Math.round(s.correct/s.questions.length*100);const wrong=s.questions.length-s.correct;const by={};s.answers.forEach(a=>{const q=questions.find(x=>x.id===a.id),name=moduleTitle(q.module);by[name]??={c:0,t:0};by[name].t++;if(a.correct)by[name].c++});$('#quizRunner').innerHTML=`<div class="result-card"><span class="eyebrow">SESSION COMPLETE</span><h1>${pct>=80?'表現很好！':pct>=60?'觀念正在建立':'先從錯題補強'}</h1><p>本次答對 ${s.correct} 題、答錯 ${wrong} 題。</p><div class="result-score"><strong>${pct}%</strong><span>正確率</span></div><div class="breakdown">${Object.entries(by).slice(0,6).map(([k,v])=>`<div><b>${v.c}/${v.t}</b><small>${escapeHTML(k)}</small></div>`).join('')}</div><div class="result-actions"><button class="btn secondary" id="newQuiz">再做一回</button>${wrong?'<button class="btn primary" id="reviewWrong">複習錯題</button>':'<button class="btn primary" id="goCourse">繼續學習</button>'}</div></div>`;$('#newQuiz').onclick=resetQuiz;if($('#reviewWrong'))$('#reviewWrong').onclick=()=>startQuiz('wrong',999);if($('#goCourse'))$('#goCourse').onclick=()=>showView('course')}
function resetQuiz(){$('#quizSetup').hidden=false;$('#quizRunner').hidden=true;$('#quizRunner').innerHTML='';quizSession=null;updateQuizAvailability()}
function renderMistakes(){const el=$('#mistakeList'),wrong=state.wrongIds.map(id=>questions.find(q=>q.id===id)).filter(Boolean);if(!wrong.length){el.innerHTML='<div class="empty-state"><span>✓</span><h2>目前沒有錯題</h2><p>完成練習後，答錯的題目會自動出現在這裡。</p><button class="btn primary" data-quick="mixed">開始 10 題練習</button></div>';el.querySelector('[data-quick]').onclick=()=>startQuiz('mixed',10);return}el.innerHTML=wrong.map(q=>`<article class="mistake-card"><div class="meta"><span>${escapeHTML(moduleTitle(q.module))}</span><span>累積作答 ${state.answerLog[q.id]?.attempts||1} 次</span></div><h3>${escapeHTML(q.prompt)}</h3><div class="answer">正確答案：${escapeHTML(q.choices[q.answer])}</div><div class="explanation">${escapeHTML(q.explanation)}${q.tip?`<br><small>提示：${escapeHTML(q.tip)}</small>`:''}</div></article>`).join('')}
function initFlashcards(){const sel=$('#flashCategory');if(!sel.options.length){const cats=['全部',...new Set(cards.map(c=>c.category))];sel.innerHTML=cats.map(x=>`<option>${escapeHTML(x)}</option>`).join('');sel.onchange=buildFlashDeck;$('#flashcard').onclick=()=>$('#flashcard').classList.toggle('flipped');$('#nextFlash').onclick=()=>moveFlash(1);$('#prevFlash').onclick=()=>moveFlash(-1);$('#shuffleFlash').onclick=buildFlashDeck;$('#masterFlash').onclick=toggleMasterCard}buildFlashDeck()}
function buildFlashDeck(){const cat=$('#flashCategory').value||'全部';flashDeck=shuffle(cards.filter(c=>cat==='全部'||c.category===cat));flashIndex=0;renderFlash()}
function moveFlash(d){if(!flashDeck.length)return;flashIndex=(flashIndex+d+flashDeck.length)%flashDeck.length;renderFlash()}
function renderFlash(){const c=flashDeck[flashIndex];if(!c)return;$('#flashcard').classList.remove('flipped');$('#flashCat').textContent=c.category;$('#flashTerm').textContent=c.term;$('#flashMeaning').textContent=c.meaning;$('#flashExample').textContent=c.example;$('#flashCounter').textContent=`${flashIndex+1} / ${flashDeck.length}`;const mastered=state.masteredCards.includes(c.term);$('#masterFlash').textContent=mastered?'✓ 已熟悉':'標記已熟悉';$('#masterFlash').classList.toggle('success',mastered)}
function toggleMasterCard(){const c=flashDeck[flashIndex];if(!c)return;if(state.masteredCards.includes(c.term))state.masteredCards=state.masteredCards.filter(x=>x!==c.term);else state.masteredCards.push(c.term);saveState();renderFlash();toast(state.masteredCards.includes(c.term)?'已標記熟悉':'已取消熟悉標記')}
function setupSearch(){const input=$('#globalSearch'),box=$('#searchResults');input.addEventListener('input',()=>{const term=input.value.trim().toLowerCase();if(term.length<2){box.hidden=true;return}const found=modules.filter(m=>(m.title+' '+m.subtitle+' '+m.keywords.join(' ')+' '+stripHTML(m.content)).toLowerCase().includes(term)).slice(0,8);box.innerHTML=found.length?found.map(m=>`<button class="search-result" data-module="${m.id}"><b>${escapeHTML(m.title)}</b><small>${escapeHTML(m.subtitle)}</small></button>`).join(''):'<div style="padding:12px;color:var(--muted)">找不到相關內容</div>';box.hidden=false;$$('.search-result').forEach(b=>b.onclick=()=>{box.hidden=true;input.value='';openModule(b.dataset.module)})});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))box.hidden=true})}
function init(){updateVisit();document.documentElement.dataset.theme=state.theme||'light';$('#quizModule').innerHTML=modules.filter(m=>questions.some(q=>q.module===m.id)).map(m=>`<option value="${m.id}">${escapeHTML(m.title)}（${questions.filter(q=>q.module===m.id).length} 題）</option>`).join('');$$('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$$('[data-quick="mixed"]').forEach(b=>b.onclick=()=>startQuiz('mixed',10));$$('.mode-card').forEach(l=>l.onclick=()=>setMode(l.querySelector('input').value));$('#startQuizBtn').onclick=()=>startQuiz($('input[name="quizMode"]:checked').value,$('#quizCount').value,$('#quizModule').value);$('#quizModule').onchange=updateQuizAvailability;$('#quizCount').onchange=updateQuizAvailability;$('#continueBtn').onclick=()=>openModule(state.lastModule||'priority');$('#clearWrongBtn').onclick=()=>{if(state.wrongIds.length&&confirm('確定要清空所有錯題嗎？')){state.wrongIds=[];saveState();renderMistakes()}};$('#themeBtn').onclick=()=>{state.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=state.theme;saveState()};$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');setupSearch();refreshStats();renderCourseNav();setMode('mixed')}
init();
})();